### ISSUE TITLE
Use of undefined constant CURLE_RECV_ERROR - assumed 'CURLE_RECV_ERROR

### ISSUE THREAD

**Issue by bhalsodkhushal** [aws/aws-sdk-php-laravel#128]
How to solve below error

exception : "ErrorException"
file : "/var/www/html/videoapp/vendor/aws/aws-sdk-php/src/Middleware.php" 
line : 185
message : "Use of undefined constant CURLE_RECV_ERROR - assumed 'CURLE_RECV_ERROR'"

**Comment by kstich** [comment]
The AWS SDK for PHP released an update in [version 3.52.0](https://github.com/aws/aws-sdk-php/releases/tag/3.52.0) that retries this specific CURLE code. [The AWS SDK for PHP requires cURL and its PHP extension to run.](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/requirements.html) This error is because you do not have the cURL PHP extension installed or configured properly.

**Comment by kstich** [comment]
Update: We're tracking [this issue on the main AWS SDK for PHP repo](https://github.com/aws/aws-sdk-php/issues/1480).

**Comment by kstich** [comment]
[This fix was released in 3.52.1](https://github.com/aws/aws-sdk-php/releases/tag/3.52.1).
