### ISSUE TITLE
Rekognition InvalidS3ObjectException Error in SearchFacesByImage (400 Bad Request.. Unable to get object metadata from S3)

### ISSUE THREAD

**Issue by pranavansp** [aws/aws-sdk-php-laravel#139]
I'm getting below error when i execute Rekognition using Image or Video. 

" Error executing "SearchFacesByImage" on "https://rekognition.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://rekognition.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response: {"__type":"InvalidS3ObjectException","Code":"InvalidS3ObjectException","Logref":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"," (truncated...) InvalidS3ObjectException (client): Unable to get object metadata from S3. Check object key, region and/or access permissions. - {"__type":"InvalidS3ObjectException","Code":"InvalidS3ObjectException.

My as code Below.
```
$credentials = new Credentials('xxxxxxxxx', 'xxxxxxxxxxxx');

$rekognitionClient = RekognitionClient::factory(array(
            'region' => "us-east-1",
            'version' => 'latest',
            'credentials' => $credentials,
            'http' => [ 'verify' => false ]
 ));
```
```
$result = $rekognitionClient->searchFacesByImage([
                    'CollectionId' => ''.$collection_id.'', // REQUIRED
                    'FaceMatchThreshold' => 25.0,
                    'Image' => [ // REQUIRED
                            'S3Object' => [
                                'Bucket' => 'facetracking',
                                'Name' => 'test.jpg',
                                'Key' => 'test.jpg',
                                'Version' => 'latest',
                            ],
                    ], 'MaxFaces' => 2,
                ]);
```

When I'm uploading into S3, Gettring object from S3 and creating collection in Rek All Its works fine but I can't execute searchFacesByImage (Source : S3)  and startFaceSearch in Laravel PHP.

Also tired after bucket policy setup in S3 like below.
```
{
    "Version": "2012-10-17",
    "Id": "PolicyXXXXXX",
    "Statement": [
        {
            "Sid": "StmtXXXXXX",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::XXXXXXXX:root"
            },
            "Action": [
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:GetObjectTagging",
                "s3:GetObjectTorrent",
                "s3:GetObjectVersion",
                "s3:GetObjectVersionAcl"
            ],
            "Resource": [
                "arn:aws:s3:::<MyBucketName>/*",
                "arn:aws:s3:::<MyBucketName>"
            ]
        }
    ]
}
```

**Comment by diehlaws** [comment]
Hey @pranavansp, thanks for reaching out about this. This behavior is reproducible across multiple SDKs, so this seems to be related to the Amazon Rekognition service rather than the AWS SDK for PHP. 

I was able to reproduce this with an S3 Bucket that did not have versioning enabled as long as I was specifying a version in `S3Object`. Commenting out `'Version' => 'latest',` resulted in the `SearchFacesByImage` call being processed successfully. Likewise, uncommenting `'Version' => 'latest',` and enabling versioning on my S3 Bucket resulted in a successful `SearchFacesByImage` call. Can you verify whether this is the case on your end?

Unfortunately, the [S3Object](https://docs.aws.amazon.com/rekognition/latest/dg/API_S3Object.html) documentation for Amazon Rekognition does not make this behavior clear. I will be reaching out to the documentation team to have the `Version` section updated to clarify that specifying a version for an unversioned bucket will result in an error response from the service. I recommend submitting feedback on this documentation page from your end as well via the Feedback button at the bottom of the page in order to raise awareness of the same.

Please keep in mind that this particular repository is for the AWS Service Provider for Laravel 5. As such, any issues submitted in this repository should be specific to this service provider and not about behavior within the AWS SDK for PHP itself. Any issues with the SDK itself should be submitted under the [AWS SDK for PHP repository](https://github.com/aws/aws-sdk-php/issues) instead.
