### ISSUE TITLE
SSL: Handshake timed out

### ISSUE THREAD

**Issue by Priyankaac209** [aws/aws-sdk-php-laravel#179]
Hi,

We are using "aws/aws-sdk-php-laravel": "^3.3".
We are calling aws sqs service.
Randomly once in hour we are getting below error.
"AWS HTTP error: Error creating resource: [message] fopen(): SSL: Handshake timed out [file]"...cntd

Can you please help us in fixing this issue?

**Comment by diehlaws** [comment]
Thanks for reaching out to us @Priyankaac209. Since you are using the AWS Service Provider for Laravel I've transferred this issue to the appropriate repo. That being said, this sounds like a connectivity issue between your host and the SQS service - having more details on the environment in which you're experiencing this behavior would be helpful. In order to rule out the SDK as the culprit of this behavior, can you provide a code sample showing which SQS call you're using when encountering this error as well as how the input for this call is being populated? Filling out the issue template would also help us better troubleshoot this behavior.

```
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?


### Version of AWS Service Provider for Laravel?


### Version of Laravel (`php artisan --version`)?


### Version of PHP (`php -v`)?


### What issue did you see?


### Steps to reproduce
If you have a runnable example, please include it as a snippet or link to a repository/gist for larger code examples.

### Additional context
Any additional information relevant to the issue, for example PHP/environment config settings if the issue is related to memory or performance.
```

**Comment by GrahamCampbell** [comment]
If you are using PHP 5.5, it is possible this can be mitigated by explicitly providing a CA file, or upgrading to PHP 5.6+.

**Comment by diehlaws** [comment]
@Priyankaac209 due to inactivity from your end on this I'll be closing out the issue for now. If you are still experiencing this behavior please provide the information requested in my comment above and we will re-open the issue so we can better assist you on this.
