### ISSUE TITLE
Error parsing response for ListBuckets: AWS parsing error: Error parsing XML: String could not be parsed as XML

### ISSUE THREAD

**Issue by abhiburk** [aws/aws-sdk-php-laravel#230]
### Describe the bug

While listing buckets I am facing this error.
`Aws \ S3 \ Exception \ S3Exception
Error parsing response for ListBuckets: AWS parsing error: Error parsing XML: String could not be parsed as XML`

### Expected Behavior

Should list down the no. of buckets for the requested Keys

### Current Behavior

Even after passing proper config in the aws.php file I am unable to get the list of the buckets using list. My endpoint is pointing towards ceph setup.

### Reproduction Steps

`$s3 = App::make('aws')->createClient('s3');

dd($s3->listBuckets());`

### SDK version used

3.8

### Environment details (OS name and version, etc.)

Windows 11, PHP 8.1.10

**Comment by yenfryherrerafeliz** [comment]
Hi @abhiburk, I see you are using an outdated SDK version so that could you please update to the latest version?. The API models change over time and probably the version that you are using does not have the proper deserializer in place for how the response is gotten as of right now from the service. I am going to try also to reproduce this by using the version you are using, but I am pretty sure that is the problem.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
@abhiburk, sorry, I see you are using the latest one for aws-sdk-php-laravel. I am going to work on reproducing this and I will get back to you as soon as possible.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @abhiburk, I just tried to reproduce the reported behavior but I could not. Could you please confirm if this is a persistent issue for you?

Thanks!
